spring:
  liquibase:
    enabled: false
    change-log: "classpath:/db/changelog/logs.yml"

  datasource:
    url: jdbc:hsqldb:~/test7
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: us
    password:

  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update