--liquibase formatted sql


--changeset db:schema-init
CREATE TABLE DEPARTMENT (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR (40)
);

CREATE TABLE JOB_POSITION (
    ID BIGSERIAL PRIMARY KEY,
    WEEK_HOURS INT,
    START_TIME TIME,
    SALARY INT
);

CREATE TABLE EMPLOYEE (
    ID BIGSERIAL PRIMARY KEY,
    ROLE VARCHAR(40) NOT NULL,
    LOGIN VARCHAR(40) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL,
    FIRST_NAME VARCHAR(40),
    LAST_NAME VARCHAR(40),
    DEPARTMENT BIGINT,
    JOB_POSITION BIGINT,
    FOREIGN KEY (JOB_POSITION) REFERENCES JOB_POSITION (ID),
    FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE WORK_LOG (
    ID BIGSERIAL PRIMARY KEY,
    EMPLOYEE BIGINT,
    DAILY DATE,
    START_TIME TIME,
    END_TIME TIME,
    DURATION BIGINT,
    FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE WORK_LOG_REPORT (
    ID BIGSERIAL PRIMARY KEY,
    EMPLOYEE BIGINT,
    START_DATE DATE,
    DURATION BIGINT,
    TYPE VARCHAR (40),
    FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE (ID)
);

CREATE TABLE DEPARTMENT_BONUS (
    ID BIGSERIAL PRIMARY KEY,
    DEPARTMENT BIGINT,
    DATES DATE,
    PAYOUT INT,
    FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE SYSTEM_PROPERTY (
    ID BIGSERIAL PRIMARY KEY,
    KEY VARCHAR (40),
    VALUE VARCHAR (40),
    DESCRIPTION VARCHAR (40)
);

--changeset db:schema-add
INSERT INTO JOB_POSITION (WEEK_HOURS, START_TIME, SALARY) VALUES (40, NULL, 5000);
INSERT INTO JOB_POSITION (WEEK_HOURS, START_TIME, SALARY) VALUES (35, NULL, 2000);
INSERT INTO DEPARTMENT (NAME) VALUES ('FIRST DEPARTMENT');
INSERT INTO EMPLOYEE (ROLE, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, DEPARTMENT, JOB_POSITION) VALUES ('USER', 'user1', 'us', 'Piter', 'Yann', 1, 1);
INSERT INTO EMPLOYEE (ROLE, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, DEPARTMENT, JOB_POSITION) VALUES ('ADMIN', 'admin', 'admin', 'Joe', 'Yambl', 1, 1);

